apiVersion: 1

datasources:
  - name: My2DB - MYSQL
    type: mysql
    typeName: MySQL
    typeLogoUrl: public/app/plugins/datasource/mysql/img/mysql_logo.svg
    access: proxy
    url: localhost:3306
    user: grafana
    database: my2
    basicAuth: false
    isDefault: true
    jsonData:
      timeInterval: 1m
    readOnly: false
    secureJsonData:
      password: test123
  - name: Loki
    type: loki
    typeName: Loki
    typeLogoUrl: public/app/plugins/datasource/loki/img/loki_icon.svg
    access: proxy
    url: localhost:3100
    basicAuth: false
    isDefault: false
    readOnly: false
  - name: Prometheus
    type: prometheus
    typeName: Prometheus
    typeLogoUrl: public/app/plugins/datasource/prometheus/img/prometheus_logo.svg
    access: proxy
    url: http://localhost:9090
    basicAuth: false
    isDefault: false
    readOnly: false
  - name: InfluxDB
    type: influxdb
    typeName: InfluxDB
    typeLogoUrl: public/app/plugins/datasource/influxdb/img/influxdb_logo.svg
    access: proxy
    url: http://localhost:8086
    basicAuth: false
    isDefault: false
    readOnly: false
    version: 2
    jsonData:
      defaultBucket: telegraf
      httpMode: POST
      organization: grafana
      version: Flux
    secureJsonData:
      token: admin

