apiVersion: 1

datasources:
  - name: My2DB - MYSQL
    type: mysql
    typeName: MySQL
    typeLogoUrl: public/app/plugins/datasource/mysql/img/mysql_logo.svg
    access: proxy
    url: localhost:3306
    user: grafana
    database: my2
    basicAuth: false
    isDefault: true
    jsonData:
      timeInterval: 1m
    readOnly: false
    secureJsonData:
      password: test123
  - name: Loki
    type: loki
    typeName: Loki
    typeLogoUrl: public/app/plugins/datasource/loki/img/loki_icon.svg
    access: proxy
    url: localhost:3100
    basicAuth: false
    isDefault: false
    readOnly: false
